DELIMITER //

ALTER TABLE log_client ADD touched BOOLEAN NOT NULL DEFAULT FALSE AFTER stamp;
ALTER TABLE log_config ADD touched BOOLEAN NOT NULL DEFAULT FALSE AFTER stamp;
ALTER TABLE log_database ADD touched BOOLEAN NOT NULL DEFAULT FALSE AFTER stamp;
ALTER TABLE log_default ADD touched BOOLEAN NOT NULL DEFAULT FALSE AFTER stamp;
ALTER TABLE log_delegation_only ADD touched BOOLEAN NOT NULL DEFAULT FALSE AFTER stamp;
ALTER TABLE log_dispatch ADD touched BOOLEAN NOT NULL DEFAULT FALSE AFTER stamp;
ALTER TABLE log_dnssec ADD touched BOOLEAN NOT NULL DEFAULT FALSE AFTER stamp;
ALTER TABLE log_general ADD touched BOOLEAN NOT NULL DEFAULT FALSE AFTER stamp;
ALTER TABLE log_lame_servers ADD touched BOOLEAN NOT NULL DEFAULT FALSE AFTER stamp;
ALTER TABLE log_network ADD touched BOOLEAN NOT NULL DEFAULT FALSE AFTER stamp;
ALTER TABLE log_notify ADD touched BOOLEAN NOT NULL DEFAULT FALSE AFTER stamp;
ALTER TABLE log_queries ADD touched BOOLEAN NOT NULL DEFAULT FALSE AFTER stamp;
ALTER TABLE log_resolver ADD touched BOOLEAN NOT NULL DEFAULT FALSE AFTER stamp;
ALTER TABLE log_security ADD touched BOOLEAN NOT NULL DEFAULT FALSE AFTER stamp;
ALTER TABLE log_unmatched ADD touched BOOLEAN NOT NULL DEFAULT FALSE AFTER stamp;
ALTER TABLE log_update ADD touched BOOLEAN NOT NULL DEFAULT FALSE AFTER stamp;
ALTER TABLE log_update_security ADD touched BOOLEAN NOT NULL DEFAULT FALSE AFTER stamp;
ALTER TABLE log_xfer_in ADD touched BOOLEAN NOT NULL DEFAULT FALSE AFTER stamp;
ALTER TABLE log_xfer_out ADD touched BOOLEAN NOT NULL DEFAULT FALSE AFTER stamp;

ALTER TABLE log_client ADD INDEX idx_touched (touched);
ALTER TABLE log_config ADD INDEX idx_touched (touched);
ALTER TABLE log_database ADD INDEX idx_touched (touched);
ALTER TABLE log_default ADD INDEX idx_touched (touched);
ALTER TABLE log_delegation_only ADD INDEX idx_touched (touched);
ALTER TABLE log_dispatch ADD INDEX idx_touched (touched);
ALTER TABLE log_dnssec ADD INDEX idx_touched (touched);
ALTER TABLE log_general ADD INDEX idx_touched (touched);
ALTER TABLE log_lame_servers ADD INDEX idx_touched (touched);
ALTER TABLE log_network ADD INDEX idx_touched (touched);
ALTER TABLE log_notify ADD INDEX idx_touched (touched);
ALTER TABLE log_queries ADD INDEX idx_touched (touched);
ALTER TABLE log_resolver ADD INDEX idx_touched (touched);
ALTER TABLE log_security ADD INDEX idx_touched (touched);
ALTER TABLE log_unmatched ADD INDEX idx_touched (touched);
ALTER TABLE log_update ADD INDEX idx_touched (touched);
ALTER TABLE log_update_security ADD INDEX idx_touched (touched);
ALTER TABLE log_xfer_in ADD INDEX idx_touched (touched);
ALTER TABLE log_xfer_out ADD INDEX idx_touched (touched);

ALTER TABLE log_client DROP INDEX idx_processed_skipped;
ALTER TABLE log_config DROP INDEX idx_processed_skipped;
ALTER TABLE log_database DROP INDEX idx_processed_skipped;
ALTER TABLE log_default DROP INDEX idx_processed_skipped;
ALTER TABLE log_delegation_only DROP INDEX idx_processed_skipped;
ALTER TABLE log_dispatch DROP INDEX idx_processed_skipped;
ALTER TABLE log_dnssec DROP INDEX idx_processed_skipped;
ALTER TABLE log_general DROP INDEX idx_processed_skipped;
ALTER TABLE log_lame_servers DROP INDEX idx_processed_skipped;
ALTER TABLE log_network DROP INDEX idx_processed_skipped;
ALTER TABLE log_notify DROP INDEX idx_processed_skipped;
ALTER TABLE log_queries DROP INDEX idx_processed_skipped;
ALTER TABLE log_resolver DROP INDEX idx_processed_skipped;
ALTER TABLE log_security DROP INDEX idx_processed_skipped;
ALTER TABLE log_unmatched DROP INDEX idx_processed_skipped;
ALTER TABLE log_update DROP INDEX idx_processed_skipped;
ALTER TABLE log_update_security DROP INDEX idx_processed_skipped;
ALTER TABLE log_xfer_in DROP INDEX idx_processed_skipped;
ALTER TABLE log_xfer_out DROP INDEX idx_processed_skipped;
